/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Restaurant res1 = new Restaurant("Mac" ,  "$$$");
//        Review rev = new Review("Very Good" , "Mohammed" , 1);
        res1.addReview("Very Good" , "Hatem Sallam" , 5);
        res1.addReview("Very Good" , "Hatem Sallam" , 4);
        res1.addReview("Very Good" , "Hatem Sallam" , 1);
        res1.addReview("Very Good" , "Hatem Sallam" , 2);
        System.out.println(res1);
        Restaurant res2 = new Restaurant("KFC" , "$$");
        res2.addReview("Very Good" , "Hatem Sallam" , 5);
        System.out.println(res2);

        Theater theater = new Theater("amman");
        theater.addMovie("Hello");
        System.out.println(theater.getMovies());
//        theater.removeMovie("Hello");
//        System.out.println(theater.getMovies());
        theater.addMovie("New Movie");
        theater.addReview(new Review("hello" , "Hatem" , 4), "Hello");
        theater.addReview(new Review("hello" , "Hatem" , 4), "Hellfo");
        theater.addReview(new Review("hello" , "Hatem" , 4));
        System.out.println(theater.getReviews());



    }
}
